version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=gHjpN29ZHA8L6BeE
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306" #mariadb-port
    restart: unless-stopped

  redis-cache:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_cache.conf"]
    restart: unless-stopped

  redis-queue:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_queue.conf"]
    restart: unless-stopped

  redis-socketio:
    image: redis:alpine
    volumes:
      - ./redis-conf:/etc/conf.d
    command: ["redis-server","/etc/conf.d/redis_socketio.conf"]
    restart: unless-stopped

  frappe:
    environment:
      - FRAPPE_VERSION=v10.1.68
      - ERPNEXT_VERSION=v10.1.68
    volumes:
      - ./scripts:/home/frappe/scripts
      - ./frappe-bench:/home/frappe/frappe-bench
      - ./redis-conf/redis_cache.conf:/home/frappe/frappe-bench/config/redis_cache.conf
      - ./redis-conf/redis_queue.conf:/home/frappe/frappe-bench/config/redis_queue.conf
      - ./redis-conf/redis_socketio.conf:/home/frappe/frappe-bench/config/redis_socketio.conf
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "/home/frappe/scripts/run.sh"
    ports:
      - "127.0.0.1:8000:8000" #webserver_port
      - "127.0.0.1:9000:9000" #socketio_port
      - "127.0.0.1:6787:6787" #file_watcher_port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    restart: unless-stopped

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/nginx_dockerfile
  #   volumes:
  #     - ./docker/nginx:/etc/nginx/conf.d:ro
  #     - ./frappe-bench:/home/frappe/frappe-bench:ro
  #   command: nginx-debug -g 'daemon off;'
  #   depends_on:
  #     - frappe
  #   links:
  #     - frappe
  #   ports:
  #     - 127.0.0.1:9090:80

  # ## TODO: prod-ready changes
  # worker:
  #   run celery; consume from default, short & long queues

  # scheduler:
  #   run: bench schedule

  # node_socketio:
  #   port: 9000
  #   run: /usr/bin/node /home/badili/frappe-bench/apps/frappe/socketio.js

  # nginx:
  #   - proxy pass to frappe
  #   - share volumes with frappe for statics